### PR TITLE
Update 06-lowflow chapter

### PR DESCRIPTION
**Pull request by ggkasman**
- changed the brackets to round parenthesis for in text references
- chunks are updated to have unique names (e.g. fig1_gamze)
- html rendering works
- pdf rendering does not work, I have been trying to fix it for the last week but could not manage it

### CODE REVIEW

**Comment by henrifnk** [comment]
Did you update branch by the master :) and then render it using
bookdown::render_book('./', 'bookdown::pdf_book', clean = FALSE)

**Comment by henrifnk** [comment]
Your diffs look pretty solid so we can try to merge anyways...

**Comment by ggkasman** [comment]
I accidentally deleted this branch and then created a new one. Requested a new PR from the new branch, sorry for that.

Yes, I did update the new branch with the master, right now it is up-to-date only one commit ahead of the master.

**Comment by ggkasman** [comment]
The new .rmd file renders to pdf as well as html. I have updated my equations (changed align with aligned) and pdf rendering worked

**Pull request closed without merging**
